@echo off
echo Starting Travel App...

echo Starting backend server...
start cmd /k "cd backend && python -m uvicorn app:app --reload --host 0.0.0.0 --port 8000"

echo Starting frontend server...
start cmd /k "cd frontend && npm run dev"

echo Both servers should be starting in separate windows.
echo Press any key to exit...
pause 